Refactoring rds backup
opentelekomcloud-infra/csm-test-scenarios pull request #10
Opened 2021-02-08 07:52 UTC by Polina-Gubina

Refactoring rds backup due to moving rds library

2021-02-08 08:02 UTC, outcatcher requested changes

2021-02-08 08:02 UTC, outcatcher commented on inventory/prod/group_vars/all.yml
> +
Please don't remove `ansible_ssh_private_key_file` from common inventory

2021-02-11 07:55 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-11 07:59 UTC, anton-sidelnikov approved these changes

2021-02-11 07:59 UTC, Polina-Gubina commented
recheck

2021-02-11 08:10 UTC, outcatcher approved these changes

2021-02-11 08:19 UTC, merged