Obs client
opentelekomcloud-infra/csm-test-scenarios pull request #3
Opened 2021-01-18 15:58 UTC by anton-sidelnikov

Script to fetch controller key and state variables
Creates var file for ansible in playbooks/vars folder

2021-01-18 16:09 UTC, lego963 submitted a review, later dismissed

2021-01-18 16:28 UTC, outcatcher requested changes

2021-01-18 16:28 UTC, outcatcher commented on playbooks/files/obs_cli.py
> +        root_path = os.path.abspath(f'{os.path.dirname(__file__)}/../..')
Can be made a constant

2021-01-18 16:28 UTC, outcatcher commented on playbooks/files/obs_cli.py
> +        variables.update(outputs)
Variables will be overwritten if there are overlapping keys

2021-01-18 16:28 UTC, outcatcher commented on playbooks/files/obs_cli.py
> +    variables.update({'controller_key': key_path})
`{'controller_key': key_path}` can be moved in dictionary declaration

2021-01-18 16:28 UTC, outcatcher commented on playbooks/files/obs_cli.py
> +    """Download existing key from s3 or create a new one and upload"""
Please change docstring, the method is used not only for the key now

2021-01-18 16:28 UTC, outcatcher commented on playbooks/files/obs_cli.py
> +            print('The object does not exist in s3. Generating new one...')
Is this print valid?

2021-01-19 09:29 UTC, Polina-Gubina submitted a review, later dismissed

2021-01-19 09:30 UTC, lego963 submitted a review, later dismissed

2021-01-19 09:38 UTC, Polina-Gubina approved these changes

2021-01-19 09:55 UTC, lego963 approved these changes

2021-01-19 10:13 UTC, outcatcher approved these changes

2021-01-19 10:17 UTC, merged